# --coding:utf-8--
# Auto-generated by RunBot maker. DO NOT EDIT manually.
from typing import Optional
from attrs import define, field

from core.api_object import BaseAPIObject
from core.router import router
from apis.member.models import SaveMemberTagAPIRequest, SaveMemberTagAPIResponse, DeleteMemberTagAPIRequest, DeleteMemberTagAPIResponse


@define(kw_only=True)
@router.post("/api/member/tag/save")
class SaveMemberTagAPI(BaseAPIObject):
    """保存成员标签"""
    request_body: Optional[SaveMemberTagAPIRequest] = field(default=None)
    _response_model_cls = SaveMemberTagAPIResponse

@define(kw_only=True)
@router.post("/api/member/tag/delete")
class DeleteMemberTagAPI(BaseAPIObject):
    """删除成员标签"""
    request_body: Optional[DeleteMemberTagAPIRequest] = field(default=None)
    _response_model_cls = DeleteMemberTagAPIResponse

