# --coding:utf-8--
# Auto-generated by RunBot maker. DO NOT EDIT manually.
from typing import Optional, Any
from attrs import define, field


@define
class SaveMemberTagAPIRequest:
    name: str = field(
        default=None,
        metadata={
            "description": "标签名称",
            "example": "VIP001",
        },
    )
    type: int = field(
        default=None,
        metadata={
            "description": "标签类型",
            "example": 1,
            "enum": [0, 1],
        },
    )


@define
class SaveMemberTagAPIResponse:
    code: Optional[int] = field(
        default=None,
    )
    message: Optional[str] = field(
        default=None,
    )
    data: Optional[dict] = field(
        default=None,
    )


@define
class DeleteMemberTagAPIRequest:
    ids: list = field(
        default=None,
        metadata={
            "description": "标签ID列表",
        },
    )


@define
class DeleteMemberTagAPIResponse:
    code: Optional[int] = field(
        default=None,
    )
