# --coding:utf-8--
# Auto-generated by RunBot maker. DO NOT EDIT manually.
from typing import Optional
from attrs import define, field

from core.api_object import BaseAPIObject
from core.router import router
from apis.live.models import GetLiveListAPIResponse


@define(kw_only=True)
@router.get("/api/live/list")
class GetLiveListAPI(BaseAPIObject):
    """获取直播列表"""
    _response_model_cls = GetLiveListAPIResponse

