# --coding:utf-8--
# Auto-generated by RunBot maker. DO NOT EDIT manually.
from typing import Optional, Any
from attrs import define, field


@define
class GetLiveListAPIResponse:
    code: Optional[int] = field(
        default=None,
    )
    data: Optional[list] = field(
        default=None,
    )
